# Generated by Django 6.1 on 2026-08-16 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnioAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveSmallIntegerField(unique=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Apoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_estudiante', models.CharField(max_length=30, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nivel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AsignacionCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('FINALIZADO', 'Finalizado')], default='ACTIVO', max_length=30)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_curso', to='sga.anioacademico')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='sga.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_curso', to='sga.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Capacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capacidades', to='sga.competencia')),
            ],
        ),
        migrations.CreateModel(
            name='CriterioCalificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=500, null=True)),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterios_calificacion', to='sga.capacidad')),
            ],
        ),
        migrations.AddField(
            model_name='competencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencias', to='sga.curso'),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateField()),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('RETIRADA', 'Retirada'), ('TRASLADADA', 'Trasladada'), ('FINALIZADA', 'Finalizada')], default='ACTIVA', max_length=30)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='sga.anioacademico')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='sga.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='IncidenciaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACADEMICA', 'Academica'), ('CONDUCTUAL', 'Conductual'), ('ASISTENCIA', 'Asistencia'), ('OTRO', 'Otro')], max_length=100)),
                ('descripcion', models.TextField()),
                ('nivel', models.CharField(blank=True, choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], max_length=30, null=True)),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=30)),
                ('fecha_registro', models.DateTimeField()),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_academicas', to='sga.matricula')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('estado_envio', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADA', 'Enviada'), ('FALLIDA', 'Fallida'), ('LEIDA', 'Leida')], default='PENDIENTE', max_length=30)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='sga.apoderado')),
                ('incidencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='sga.incidenciaacademica')),
            ],
        ),
        migrations.CreateModel(
            name='ObservacionAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('asignacion_curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_academicas', to='sga.asignacioncurso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_registradas', to='sga.docente')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observaciones_academicas', to='sga.matricula')),
            ],
        ),
        migrations.AddField(
            model_name='incidenciaacademica',
            name='observacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_generadas', to='sga.observacionacademica'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='estudiante',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to='sga.perfil'),
        ),
        migrations.AddField(
            model_name='docente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='docente', to='sga.perfil'),
        ),
        migrations.AddField(
            model_name='apoderado',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='apoderado', to='sga.perfil'),
        ),
        migrations.CreateModel(
            name='PeriodoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('ACTIVO', 'Activo'), ('CERRADO', 'Cerrado')], default='PLANIFICADO', max_length=30)),
                ('anio_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periodos', to='sga.anioacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('ORAL', 'Oral'), ('ESCRITA', 'Escrita'), ('PRACTICA', 'Practica'), ('OTRO', 'Otro')], max_length=100)),
                ('valor', models.CharField(blank=True, max_length=20, null=True)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('asignacion_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='sga.asignacioncurso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='sga.matricula')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='participaciones', to='sga.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=500, null=True)),
                ('asignacion_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='sga.asignacioncurso')),
                ('criterio_calificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='sga.criteriocalificacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='sga.matricula')),
                ('periodo_academico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='calificaciones', to='sga.periodoacademico')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_contexto', models.TextField()),
                ('texto_generado', models.TextField()),
                ('texto_revisado', models.TextField(blank=True, null=True)),
                ('estado_revision', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EDITADA', 'Editada')], default='PENDIENTE', max_length=30)),
                ('fecha_generacion', models.DateTimeField()),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_ia', to='sga.matricula')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recomendaciones_ia', to='sga.periodoacademico')),
                ('revisado_por_docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomendaciones_ia_revisadas', to='sga.docente')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=100)),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_auditoria_sga', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='secciones', to='sga.grado')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matriculas', to='sga.seccion'),
        ),
        migrations.AddField(
            model_name='asignacioncurso',
            name='seccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones_curso', to='sga.seccion'),
        ),
        migrations.CreateModel(
            name='VinculoApoderado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentesco', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('TUTOR', 'Tutor'), ('OTRO', 'Otro')], max_length=50)),
                ('es_principal', models.BooleanField(default=False)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_estudiantes', to='sga.apoderado')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_apoderados', to='sga.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('TARDE', 'Tarde'), ('FALTA', 'Falta'), ('JUSTIFICADA', 'Justificada')], max_length=30)),
                ('justificacion', models.CharField(blank=True, max_length=500, null=True)),
                ('asignacion_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='sga.asignacioncurso')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asistencias', to='sga.matricula')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('matricula', 'asignacion_curso', 'fecha'), name='unique_asistencia_matricula_curso_fecha')],
            },
        ),
        migrations.AddConstraint(
            model_name='periodoacademico',
            constraint=models.UniqueConstraint(fields=('anio_academico', 'nombre'), name='unique_periodo_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='calificacion',
            constraint=models.UniqueConstraint(fields=('matricula', 'asignacion_curso', 'periodo_academico', 'criterio_calificacion'), name='unique_calificacion_matricula_curso_periodo_criterio'),
        ),
        migrations.AddConstraint(
            model_name='matricula',
            constraint=models.UniqueConstraint(fields=('estudiante', 'anio_academico'), name='unique_matricula_estudiante_anio'),
        ),
        migrations.AddConstraint(
            model_name='asignacioncurso',
            constraint=models.UniqueConstraint(fields=('curso', 'seccion', 'anio_academico'), name='unique_asignacion_curso_seccion_anio'),
        ),
        migrations.AddConstraint(
            model_name='vinculoapoderado',
            constraint=models.UniqueConstraint(fields=('apoderado', 'estudiante'), name='unique_vinculo_apoderado_estudiante'),
        ),
    ]
