# Generated by Django 6.1 on 2026-08-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0002_anioacademico_activo_grado_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='observacionacademica',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
