# Generated by Django 6.1 on 2026-08-17 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0003_observacionacademica_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
