# Generated by Django 6.1 on 2026-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0004_notificacion_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacionia',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
