# Generated by Django 6.1 on 2026-08-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0005_recomendacionia_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionInstitucional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=200)),
                ('codigo_modular', models.CharField(blank=True, max_length=30, null=True)),
                ('direccion', models.CharField(blank=True, max_length=250, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('director', models.CharField(blank=True, max_length=150, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('zona_horaria', models.CharField(default='America/Lima', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio_academico_activo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configuraciones_activas', to='sga.anioacademico')),
            ],
            options={
                'verbose_name': 'Configuracion institucional',
                'verbose_name_plural': 'Configuraciones institucionales',
            },
        ),
    ]
