# Generated by Django 6.1 on 2026-08-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0007_estados_academicos_enteros'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacidad',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='competencia',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
        migrations.AddField(
            model_name='criteriocalificacion',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inactivo'), (1, 'Activo')], default=1),
        ),
        migrations.AddConstraint(
            model_name='capacidad',
            constraint=models.UniqueConstraint(fields=('competencia', 'nombre'), name='unique_capacidad_por_competencia'),
        ),
        migrations.AddConstraint(
            model_name='competencia',
            constraint=models.UniqueConstraint(fields=('curso', 'nombre'), name='unique_competencia_por_curso'),
        ),
        migrations.AddConstraint(
            model_name='criteriocalificacion',
            constraint=models.UniqueConstraint(fields=('capacidad', 'nombre'), name='unique_criterio_por_capacidad'),
        ),
    ]
