# Generated by Django 6.1 on 2026-08-21 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0008_capacidad_estado_competencia_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grado',
            name='nivel',
        ),
    ]
