# Generated by Django 6.1 on 2026-08-30 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0012_correoinstitucional'),
    ]

    operations = [
        migrations.AddField(
            model_name='correoinstitucional',
            name='asignacion_curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_institucionales', to='sga.asignacioncurso'),
        ),
        migrations.AddField(
            model_name='correoinstitucional',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_institucionales', to='sga.incidenciaacademica'),
        ),
        migrations.AddField(
            model_name='correoinstitucional',
            name='matricula',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_institucionales', to='sga.matricula'),
        ),
        migrations.AddField(
            model_name='correoinstitucional',
            name='periodo_academico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_institucionales', to='sga.periodoacademico'),
        ),
        migrations.AddField(
            model_name='correoinstitucional',
            name='recomendacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correos_institucionales', to='sga.recomendacionia'),
        ),
        migrations.AddField(
            model_name='correoinstitucional',
            name='tipo',
            field=models.CharField(choices=[('INSTITUCIONAL', 'Institucional'), ('CALIFICACIONES', 'Calificaciones'), ('RECOMENDACION', 'Recomendacion'), ('INCIDENCIA', 'Incidencia'), ('ASISTENCIA', 'Asistencia'), ('SEGUIMIENTO', 'Seguimiento')], default='INSTITUCIONAL', max_length=30),
        ),
    ]
