# Generated by Django 6.1 on 2026-09-04 03:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0013_correoinstitucional_asignacion_curso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioMFA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(max_length=128)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('expira_en', models.DateTimeField()),
                ('intentos', models.PositiveSmallIntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desafios_mfa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['user', 'usado', 'expira_en'], name='sga_desafio_user_id_b8e4f9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoAutenticacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LOGIN_EXITOSO', 'Inicio de sesion exitoso'), ('LOGIN_FALLIDO', 'Inicio de sesion fallido'), ('MFA_SOLICITADO', 'MFA solicitado'), ('MFA_EXITOSO', 'MFA exitoso'), ('MFA_FALLIDO', 'MFA fallido'), ('LOGOUT', 'Cierre de sesion'), ('PASSWORD_RESET_SOLICITADO', 'Recuperacion solicitada'), ('PASSWORD_RESET_ENVIADO', 'Recuperacion enviada'), ('PASSWORD_RESET_COMPLETADO', 'Contrasena recuperada'), ('PASSWORD_CAMBIADO', 'Contrasena cambiada')], max_length=40)),
                ('exitoso', models.BooleanField(default=False)),
                ('identificador_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255, null=True)),
                ('detalle', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_autenticacion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-id'),
                'indexes': [models.Index(fields=['user', 'fecha'], name='sga_eventoa_user_id_2ae1d7_idx'), models.Index(fields=['tipo', 'fecha'], name='sga_eventoa_tipo_6249e9_idx')],
            },
        ),
    ]
