# Generated by Django 6.1 on 2026-09-11 04:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def completar_notificaciones_existentes(apps, schema_editor):
    Notificacion = apps.get_model('sga', 'Notificacion')
    for notificacion in Notificacion.objects.all():
        campos = []
        if notificacion.apoderado_id:
            notificacion.destinatario_id = notificacion.apoderado.perfil.user_id
            notificacion.accion_url = '/apoderado/notificaciones'
            campos.extend(['destinatario', 'accion_url'])
        if notificacion.incidencia_id:
            notificacion.tipo = 'INCIDENCIA'
            observacion = notificacion.incidencia.observacion
            if observacion_id := getattr(notificacion.incidencia, 'observacion_id', None):
                notificacion.enviado_por_docente_id = observacion.docente_id
                campos.append('enviado_por_docente')
            campos.append('tipo')
        if notificacion.fecha_envio:
            notificacion.creado_en = notificacion.fecha_envio
            campos.append('creado_en')
        if notificacion.estado_envio == 'LEIDA':
            notificacion.estado_envio = 'ENVIADA'
            campos.append('estado_envio')
        if campos:
            notificacion.save(update_fields=list(dict.fromkeys(campos)))


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0014_desafiomfa_eventoautenticacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='accion_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='creado_en',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='datos',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='destinatario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='detalle_error',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='enviado_por_docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones_enviadas', to='sga.docente'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('ACADEMICA', 'Academica'), ('ASISTENCIA', 'Asistencia'), ('CALIFICACION', 'Calificacion'), ('INCIDENCIA', 'Incidencia'), ('RECOMENDACION', 'Recomendacion'), ('INSTITUCIONAL', 'Institucional')], default='ACADEMICA', max_length=30),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='apoderado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='sga.apoderado'),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='incidencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='sga.incidenciaacademica'),
        ),
        migrations.RunPython(completar_notificaciones_existentes, migrations.RunPython.noop),
    ]
