# Generated by Django 6.1 on 2026-09-11 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0015_notificaciones_multirrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='recomendacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='sga.recomendacionia'),
        ),
    ]
