# Generated by Django 6.1 on 2026-09-12 18:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0016_notificacion_recomendacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccionSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REFUERZO', 'Refuerzo academico'), ('TUTORIA', 'Tutoria'), ('RECUPERACION', 'Actividad de recuperacion'), ('COMPROMISO', 'Compromiso del estudiante'), ('COMUNICACION_FAMILIA', 'Comunicacion con la familia'), ('OTRO', 'Otro')], max_length=30)),
                ('responsable', models.CharField(choices=[('DOCENTE', 'Docente'), ('ESTUDIANTE', 'Estudiante'), ('APODERADO', 'Apoderado'), ('COMPARTIDA', 'Responsabilidad compartida')], max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('NORMAL', 'Normal'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='NORMAL', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En progreso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('resultado', models.TextField(blank=True, null=True)),
                ('visible_estudiante', models.BooleanField(default=True)),
                ('visible_apoderado', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignacion_curso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.asignacioncurso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.docente')),
                ('incidencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.incidenciaacademica')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.matricula')),
                ('periodo_academico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.periodoacademico')),
                ('recomendacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones_seguimiento', to='sga.recomendacionia')),
            ],
            options={
                'ordering': ('estado', 'fecha_limite', '-creado_en'),
            },
        ),
        migrations.CreateModel(
            name='ActualizacionAccionSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMENTARIO', 'Comentario'), ('AVANCE', 'Avance'), ('EVIDENCIA', 'Evidencia')], default='COMENTARIO', max_length=20)),
                ('comentario', models.TextField()),
                ('progreso', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actualizaciones', to='sga.accionseguimiento')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actualizaciones_seguimiento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('creado_en', 'id'),
            },
        ),
        migrations.AddIndex(
            model_name='accionseguimiento',
            index=models.Index(fields=['docente', 'estado', 'fecha_limite'], name='sga_accions_docente_ba7641_idx'),
        ),
        migrations.AddIndex(
            model_name='accionseguimiento',
            index=models.Index(fields=['matricula', 'estado'], name='sga_accions_matricu_2bc009_idx'),
        ),
    ]
