# Generated by Django 6.1 on 2026-09-13 03:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0017_acciones_seguimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoCloud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('JUSTIFICACION', 'Justificacion de inasistencia'), ('BACKUP', 'Respaldo de base de datos')], max_length=30)),
                ('clave_s3', models.CharField(max_length=255, unique=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=15)),
                ('tamano', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(blank=True, max_length=64, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de carga'), ('DISPONIBLE', 'Disponible'), ('ERROR', 'Error'), ('ELIMINADO', 'Eliminado logicamente')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_cloud_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_creacion', '-id'),
            },
        ),
        migrations.CreateModel(
            name='BackupBaseDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automatico'), ('PRE_RESTAURACION', 'Previo a restauracion')], max_length=30)),
                ('estado', models.CharField(choices=[('PROCESANDO', 'Procesando'), ('DISPONIBLE', 'Disponible'), ('RESTAURANDO', 'Restaurando'), ('RESTAURADO', 'Restaurado'), ('ERROR', 'Error'), ('ELIMINADO', 'Eliminado logicamente')], default='PROCESANDO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_restauracion', models.DateTimeField(blank=True, null=True)),
                ('manifiesto', models.JSONField(blank=True, default=dict)),
                ('detalle_error', models.CharField(blank=True, max_length=500, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('archivo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='backup_base_datos', to='sga.archivocloud')),
                ('iniciado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_iniciados', to=settings.AUTH_USER_MODEL)),
                ('restaurado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups_restaurados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha_creacion', '-id'),
            },
        ),
        migrations.CreateModel(
            name='JustificacionInasistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('estado', models.CharField(choices=[('PENDIENTE_CARGA', 'Pendiente de carga'), ('PENDIENTE_REVISION', 'Pendiente de revision'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ELIMINADA', 'Eliminada logicamente')], default='PENDIENTE_CARGA', max_length=30)),
                ('comentario_revision', models.CharField(blank=True, max_length=500, null=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('apoderado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones_inasistencia', to='sga.apoderado')),
                ('archivo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='justificacion_inasistencia', to='sga.archivocloud')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sustentos', to='sga.asistencia')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='justificaciones_revisadas', to='sga.docente')),
            ],
            options={
                'ordering': ('-fecha_solicitud', '-id'),
            },
        ),
        migrations.AddIndex(
            model_name='archivocloud',
            index=models.Index(fields=['tipo', 'estado', 'fecha_creacion'], name='sga_archivo_tipo_d303fb_idx'),
        ),
        migrations.AddIndex(
            model_name='backupbasedatos',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='sga_backupb_estado_b1de78_idx'),
        ),
        migrations.AddIndex(
            model_name='justificacioninasistencia',
            index=models.Index(fields=['apoderado', 'estado'], name='sga_justifi_apodera_f306df_idx'),
        ),
        migrations.AddIndex(
            model_name='justificacioninasistencia',
            index=models.Index(fields=['asistencia', 'estado'], name='sga_justifi_asisten_b9e527_idx'),
        ),
    ]
