# Generated by Django 6.1 on 2026-09-13 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0018_archivocloud_backupbasedatos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivocloud',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='backupbasedatos',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='justificacioninasistencia',
            name='activo',
        ),
    ]
