from django.urls import include, path
from rest_framework.routers import DefaultRouter

from .api import (
    AnioAcademicoViewSet,
    ApoderadoViewSet,
    AsignacionCursoViewSet,
    ConfiguracionInstitucionalViewSet,
    CapacidadViewSet,
    CompetenciaViewSet,
    CriterioCalificacionViewSet,
    CursoViewSet,
    DocenteViewSet,
    EstudianteViewSet,
    GradoViewSet,
    IncidenciaAcademicaViewSet,
    MatriculaViewSet,
    NotificacionViewSet,
    CorreoInstitucionalViewSet,
    comunicaciones_docente,
    detalle_comunicacion_docente,
    enviar_comunicacion,
    previsualizar_comunicacion,
    ObservacionAcademicaViewSet,
    PeriodoAcademicoViewSet,
    RecomendacionIAViewSet,
    RegistroAuditoriaViewSet,
    SeccionViewSet,
    UsuarioViewSet,
    VinculoApoderadoViewSet,
    dashboard,
    actualizar_asistencia,
    actualizar_calificacion,
    actualizar_observacion,
    actualizar_participacion,
    asistencias_docente,
    calificaciones_docente,
    capacidades_mi_curso,
    criterios_mi_curso,
    estudiantes_mi_curso,
    me,
    menu,
    mis_cursos,
    observaciones_docente,
    periodos_mi_curso,
    participaciones_docente,
    reporte_academico,
    reporte_incidencias,
    reporte_matriculas,
    reporte_notificaciones,
    reporte_resumen,
    exportar_reporte_pdf,
    registrar_asistencias,
    registrar_calificaciones,
    registrar_observacion,
    registrar_participacion,
    eliminar_observacion,
    detalle_seguimiento_docente,
    detalle_recomendacion,
    seguimiento_docente,
    seguimiento_docente_admin,
    seguimiento_docentes_admin,
    accion_seguimiento_docente_detalle,
    acciones_seguimiento_administracion,
    acciones_seguimiento_apoderado,
    acciones_seguimiento_docente,
    acciones_seguimiento_estudiante,
    actualizar_progreso_apoderado,
    actualizar_progreso_docente,
    actualizar_progreso_estudiante,
    generar_recomendacion,
    publicar_recomendacion,
    recomendaciones_docente,
    revisar_recomendacion,
    mis_cursos_estudiante,
    mi_asistencia,
    mis_calificaciones,
    mi_participacion,
    mi_seguimiento,
    mis_estudiantes_apoderado,
    asistencia_apoderado,
    calificaciones_apoderado,
    seguimiento_apoderado,
    marcar_notificacion_leida,
    mis_notificaciones,
    mis_notificaciones_usuario,
    resumen_notificaciones_usuario,
    marcar_notificacion_usuario_leida,
    marcar_todas_notificaciones_leidas,
    destinatarios_notificacion_docente,
    enviar_notificacion_docente,
    notificaciones_enviadas_docente,
    carga_masiva_estudiantes,
    plantilla_carga_estudiantes,
    carga_masiva_apoderados,
    plantilla_carga_apoderados,
    reporte_docente_asistencias,
    reporte_docente_calificaciones,
    reporte_docente_resumen,
    reporte_docente_seguimiento,
    backups_administracion,
    confirmar_carga,
    crear_backup_administracion,
    detalle_backup_administracion,
    descargar_backup_administracion,
    descargar_justificacion,
    detalle_justificacion_docente,
    justificaciones_administracion,
    justificaciones_apoderado,
    justificaciones_docente,
    justificaciones_estudiante,
    retirar_justificacion,
    restaurar_backup_administracion,
    revisar_justificacion_docente,
    solicitar_carga,
)

router = DefaultRouter()
router.register("usuarios", UsuarioViewSet, basename="usuario")
router.register("estudiantes", EstudianteViewSet, basename="estudiante")
router.register("docentes", DocenteViewSet, basename="docente")
router.register("apoderados", ApoderadoViewSet, basename="apoderado")
router.register("vinculos-apoderados", VinculoApoderadoViewSet, basename="vinculo-apoderado")
router.register("matriculas", MatriculaViewSet, basename="matricula")
router.register("observaciones", ObservacionAcademicaViewSet, basename="observacion")
router.register("incidencias", IncidenciaAcademicaViewSet, basename="incidencia")
router.register("notificaciones", NotificacionViewSet, basename="notificacion")
router.register("correos", CorreoInstitucionalViewSet, basename="correo")
router.register("recomendaciones-ia", RecomendacionIAViewSet, basename="recomendacion-ia")
router.register("anios-academicos", AnioAcademicoViewSet, basename="anio-academico")
router.register("periodos", PeriodoAcademicoViewSet, basename="periodo-academico")
router.register("grados", GradoViewSet, basename="grado")
router.register("secciones", SeccionViewSet, basename="seccion")
router.register("cursos", CursoViewSet, basename="curso")
router.register("competencias", CompetenciaViewSet, basename="competencia")
router.register("capacidades", CapacidadViewSet, basename="capacidad")
router.register(
    "criterios-calificacion",
    CriterioCalificacionViewSet,
    basename="criterio-calificacion",
)
router.register("asignaciones-cursos", AsignacionCursoViewSet, basename="asignacion-curso")
router.register("auditoria", RegistroAuditoriaViewSet, basename="auditoria")
router.register("configuracion", ConfiguracionInstitucionalViewSet, basename="configuracion")

urlpatterns = [
    path("auth/me/", me, name="api-auth-me"),
    path("auth/menu/", menu, name="api-auth-menu"),
    path("dashboard/", dashboard, name="api-dashboard"),
    path("notificaciones/mias/", mis_notificaciones_usuario, name="api-notificaciones-mias"),
    path("notificaciones/mias/resumen/", resumen_notificaciones_usuario, name="api-notificaciones-resumen"),
    path("notificaciones/mias/marcar-todas-leidas/", marcar_todas_notificaciones_leidas, name="api-notificaciones-marcar-todas"),
    path("notificaciones/mias/<int:notificacion_id>/marcar-leida/", marcar_notificacion_usuario_leida, name="api-notificaciones-marcar-leida"),
    path("docente/notificaciones/destinatarios/", destinatarios_notificacion_docente, name="api-docente-notificaciones-destinatarios"),
    path("docente/notificaciones/enviar/", enviar_notificacion_docente, name="api-docente-notificaciones-enviar"),
    path("docente/notificaciones/enviadas/", notificaciones_enviadas_docente, name="api-docente-notificaciones-enviadas"),
    path(
        "administracion/seguimiento/docentes/",
        seguimiento_docentes_admin,
        name="api-seguimiento-docentes-admin",
    ),
    path(
        "administracion/seguimiento/docentes/<int:docente_id>/",
        seguimiento_docente_admin,
        name="api-seguimiento-docente-admin",
    ),
    path("docente/mis-cursos/", mis_cursos, name="api-docente-mis-cursos"),
    path(
        "docente/mis-cursos/<int:asignacion_id>/estudiantes/",
        estudiantes_mi_curso,
        name="api-docente-estudiantes-mi-curso",
    ),
    path(
        "docente/mis-cursos/<int:asignacion_id>/periodos/",
        periodos_mi_curso,
        name="api-docente-periodos-mi-curso",
    ),
    path(
        "docente/mis-cursos/<int:asignacion_id>/capacidades/",
        capacidades_mi_curso,
        name="api-docente-capacidades-mi-curso",
    ),
    path(
        "docente/mis-cursos/<int:asignacion_id>/criterios/",
        criterios_mi_curso,
        name="api-docente-criterios-mi-curso",
    ),
    path(
        "docente/asistencias/",
        asistencias_docente,
        name="api-docente-asistencias",
    ),
    path(
        "docente/asistencias/registrar/",
        registrar_asistencias,
        name="api-docente-registrar-asistencias",
    ),
    path(
        "docente/asistencias/<int:asistencia_id>/",
        actualizar_asistencia,
        name="api-docente-actualizar-asistencia",
    ),
    path(
        "docente/calificaciones/",
        calificaciones_docente,
        name="api-docente-calificaciones",
    ),
    path(
        "docente/calificaciones/registrar/",
        registrar_calificaciones,
        name="api-docente-registrar-calificaciones",
    ),
    path(
        "docente/calificaciones/<int:calificacion_id>/",
        actualizar_calificacion,
        name="api-docente-actualizar-calificacion",
    ),
    path(
        "docente/participaciones/",
        participaciones_docente,
        name="api-docente-participaciones",
    ),
    path(
        "docente/participaciones/registrar/",
        registrar_participacion,
        name="api-docente-registrar-participacion",
    ),
    path(
        "docente/participaciones/<int:participacion_id>/",
        actualizar_participacion,
        name="api-docente-actualizar-participacion",
    ),
    path(
        "docente/observaciones/",
        observaciones_docente,
        name="api-docente-observaciones",
    ),
    path(
        "docente/observaciones/registrar/",
        registrar_observacion,
        name="api-docente-registrar-observacion",
    ),
    path(
        "docente/observaciones/<int:observacion_id>/",
        actualizar_observacion,
        name="api-docente-actualizar-observacion",
    ),
    path(
        "docente/observaciones/<int:observacion_id>/eliminar/",
        eliminar_observacion,
        name="api-docente-eliminar-observacion",
    ),
    path(
        "docente/seguimiento/",
        seguimiento_docente,
        name="api-docente-seguimiento",
    ),
    path(
        "docente/seguimiento/<int:matricula_id>/",
        detalle_seguimiento_docente,
        name="api-docente-detalle-seguimiento",
    ),
    path(
        "docente/acciones-seguimiento/",
        acciones_seguimiento_docente,
        name="api-docente-acciones-seguimiento",
    ),
    path(
        "docente/acciones-seguimiento/<int:accion_id>/",
        accion_seguimiento_docente_detalle,
        name="api-docente-accion-seguimiento-detalle",
    ),
    path(
        "docente/acciones-seguimiento/<int:accion_id>/actualizaciones/",
        actualizar_progreso_docente,
        name="api-docente-actualizar-progreso",
    ),
    path(
        "estudiante/acciones-seguimiento/",
        acciones_seguimiento_estudiante,
        name="api-estudiante-acciones-seguimiento",
    ),
    path(
        "estudiante/acciones-seguimiento/<int:accion_id>/actualizaciones/",
        actualizar_progreso_estudiante,
        name="api-estudiante-actualizar-progreso",
    ),
    path(
        "apoderado/acciones-seguimiento/",
        acciones_seguimiento_apoderado,
        name="api-apoderado-acciones-seguimiento",
    ),
    path(
        "apoderado/acciones-seguimiento/<int:accion_id>/actualizaciones/",
        actualizar_progreso_apoderado,
        name="api-apoderado-actualizar-progreso",
    ),
    path(
        "administracion/acciones-seguimiento/",
        acciones_seguimiento_administracion,
        name="api-administracion-acciones-seguimiento",
    ),
    path("docente/recomendaciones-ia/", recomendaciones_docente, name="api-docente-recomendaciones"),
    path("docente/comunicaciones/", comunicaciones_docente, name="api-docente-comunicaciones"),
    path("docente/comunicaciones/previsualizar/", previsualizar_comunicacion, name="api-docente-previsualizar-comunicacion"),
    path("docente/comunicaciones/enviar/", enviar_comunicacion, name="api-docente-enviar-comunicacion"),
    path("docente/comunicaciones/<int:correo_id>/", detalle_comunicacion_docente, name="api-docente-detalle-comunicacion"),
    path("docente/recomendaciones-ia/generar/", generar_recomendacion, name="api-docente-generar-recomendacion"),
    path(
        "docente/recomendaciones-ia/<int:recomendacion_id>/",
        detalle_recomendacion,
        name="api-docente-detalle-recomendacion",
    ),
    path(
        "docente/recomendaciones-ia/<int:recomendacion_id>/revisar/",
        revisar_recomendacion,
        name="api-docente-revisar-recomendacion",
    ),
    path(
        "docente/recomendaciones-ia/<int:recomendacion_id>/publicar/",
        publicar_recomendacion,
        name="api-docente-publicar-recomendacion",
    ),
    path("docente/reportes/resumen/", reporte_docente_resumen, name="api-docente-reporte-resumen"),
    path("docente/reportes/asistencias/", reporte_docente_asistencias, name="api-docente-reporte-asistencias"),
    path("docente/reportes/calificaciones/", reporte_docente_calificaciones, name="api-docente-reporte-calificaciones"),
    path("docente/reportes/seguimiento/", reporte_docente_seguimiento, name="api-docente-reporte-seguimiento"),
    path("estudiante/mis-cursos/", mis_cursos_estudiante, name="api-estudiante-mis-cursos"),
    path("estudiante/mi-asistencia/", mi_asistencia, name="api-estudiante-mi-asistencia"),
    path("estudiante/mis-calificaciones/", mis_calificaciones, name="api-estudiante-mis-calificaciones"),
    path("estudiante/mi-participacion/", mi_participacion, name="api-estudiante-mi-participacion"),
    path("estudiante/mi-seguimiento/", mi_seguimiento, name="api-estudiante-mi-seguimiento"),
    path("apoderado/mis-estudiantes/", mis_estudiantes_apoderado, name="api-apoderado-mis-estudiantes"),
    path("apoderado/asistencia/", asistencia_apoderado, name="api-apoderado-asistencia"),
    path("apoderado/calificaciones/", calificaciones_apoderado, name="api-apoderado-calificaciones"),
    path("apoderado/seguimiento/", seguimiento_apoderado, name="api-apoderado-seguimiento"),
    path("apoderado/notificaciones/", mis_notificaciones, name="api-apoderado-notificaciones"),
    path("apoderado/notificaciones/<int:notificacion_id>/marcar-leida/", marcar_notificacion_leida, name="api-apoderado-marcar-notificacion-leida"),
    path("apoderado/justificaciones/", justificaciones_apoderado, name="api-apoderado-justificaciones"),
    path("apoderado/justificaciones/solicitar-carga/", solicitar_carga, name="api-apoderado-solicitar-carga-justificacion"),
    path("apoderado/justificaciones/<int:justificacion_id>/confirmar/", confirmar_carga, name="api-apoderado-confirmar-carga-justificacion"),
    path("apoderado/justificaciones/<int:justificacion_id>/", retirar_justificacion, name="api-apoderado-retirar-justificacion"),
    path("docente/justificaciones/", justificaciones_docente, name="api-docente-justificaciones"),
    path("docente/justificaciones/<int:justificacion_id>/", detalle_justificacion_docente, name="api-docente-detalle-justificacion"),
    path("docente/justificaciones/<int:justificacion_id>/revisar/", revisar_justificacion_docente, name="api-docente-revisar-justificacion"),
    path("estudiante/justificaciones/", justificaciones_estudiante, name="api-estudiante-justificaciones"),
    path("administracion/justificaciones/", justificaciones_administracion, name="api-administracion-justificaciones"),
    path("justificaciones/<int:justificacion_id>/descarga/", descargar_justificacion, name="api-descargar-justificacion"),
    path("administracion/backups/", backups_administracion, name="api-administracion-backups"),
    path("administracion/backups/crear/", crear_backup_administracion, name="api-administracion-crear-backup"),
    path("administracion/backups/<int:backup_id>/", detalle_backup_administracion, name="api-administracion-detalle-backup"),
    path("administracion/backups/<int:backup_id>/descarga/", descargar_backup_administracion, name="api-administracion-descargar-backup"),
    path("administracion/backups/<int:backup_id>/restaurar/", restaurar_backup_administracion, name="api-administracion-restaurar-backup"),
    path("estudiantes/carga-masiva/", carga_masiva_estudiantes, name="api-carga-masiva-estudiantes"),
    path("estudiantes/carga-masiva/plantilla/", plantilla_carga_estudiantes, name="api-plantilla-carga-estudiantes"),
    path("apoderados/carga-masiva/", carga_masiva_apoderados, name="api-carga-masiva-apoderados"),
    path("apoderados/carga-masiva/plantilla/", plantilla_carga_apoderados, name="api-plantilla-carga-apoderados"),
    path("reportes/resumen/", reporte_resumen, name="api-reporte-resumen"),
    path("reportes/exportar-pdf/", exportar_reporte_pdf, name="api-reporte-exportar-pdf"),
    path("reportes/matriculas/", reporte_matriculas, name="api-reporte-matriculas"),
    path("reportes/incidencias/", reporte_incidencias, name="api-reporte-incidencias"),
    path("reportes/notificaciones/", reporte_notificaciones, name="api-reporte-notificaciones"),
    path("reportes/academico/", reporte_academico, name="api-reporte-academico"),
    path("", include(router.urls)),
]
